[package]
org = "ob"
name = "OB_mediation_policy_service"
version = "0.1.0"
distribution = "2201.10.3"


[build-options]
observabilityIncluded = true


[[platform.java17.dependency]]
path= "JSONSchema-1.0-SNAPSHOT.jar"

# [[platform.java17.dependency]]
# groupId = "org.example"
# artifactId = "JSONSchema"
# version = "1.0-SNAPSHOT"

# # transitive dependency of org.example:JSONSchema:1.0-SNAPSHOT
# [[platform.java17.dependency]]
# groupId = "com.networknt"
# artifactId = "json-schema-validator"
# version = "1.4.0"

# # transitive dependency of com.networknt:json-schema-validator:1.4.0
# [[platform.java17.dependency]]
# groupId = "com.ethlo.time"
# artifactId = "itu"
# version = "1.8.0"

# # transitive dependency of com.networknt:json-schema-validator:1.4.0
# [[platform.java17.dependency]]
# groupId = "com.fasterxml.jackson.core"
# artifactId = "jackson-databind"
# version = "2.15.3"

# # transitive dependency of com.networknt:json-schema-validator:1.4.0
# [[platform.java17.dependency]]
# groupId = "com.fasterxml.jackson.core"
# artifactId = "jackson-annotations"
# version = "2.15.3"

# # transitive dependency of com.networknt:json-schema-validator:1.4.0
# [[platform.java17.dependency]]
# groupId = "com.fasterxml.jackson.core"
# artifactId = "jackson-core"
# version = "2.15.3"

# # transitive dependency of com.networknt:json-schema-validator:1.4.0
# [[platform.java17.dependency]]
# groupId = "com.fasterxml.jackson.dataformat"
# artifactId = "jackson-dataformat-yaml"
# version = "2.15.3"

# # transitive dependency of com.networknt:json-schema-validator:1.4.0
# [[platform.java17.dependency]]
# groupId = "org.yaml"
# artifactId = "snakeyaml"
# version = "2.1"

# # transitive dependency of com.networknt:json-schema-validator:1.4.0
# [[platform.java17.dependency]]
# groupId = "org.slf4j"
# artifactId = "slf4j-api"
# version = "2.0.9"
